### ISSUE TITLE
DSKEYS ni qatga solamiza ?

### ISSUE THREAD

**Issue by Maxmudjon** [kholmukhamedovme/e-imzo#1]

**Comment by kholmukhamedovme** [comment]
Assalomu aleykum! DSKEYS flash drive'da qolar edi, lekin bu aniq emas. Aniq esimda yo'q, ancha bo'ldi e-imzo'ni ishlatmaganimga.

**Comment by Maxmudjon** [comment]
ok raxmat

**Comment by khalmurad** [comment]
Assalomu alaykum.
Quyidagi linkda E-IMZO ni MacOS ga o'rnatib ishlatish haqida ishlaydigan video qo'llanma bor:
https://youtu.be/3CodERc7v2I?si=rLyf001DNx7tX0_L

O'zimda Macbook Pro M1. Shunga o'rnatdim, muammosiz ishlayabdi.
